### PR TITLE
Fix overflow issue when using high precision currencies

### PR DESCRIPTION
**Pull request by KOGI**
This fixes issue #51

### CODE REVIEW

**Comment by bsutton** [comment]
Bob,
appreciate the work.
Released in 2.2.2 which is now available on pub.dev.

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by KOGI** [comment]
@bsutton just wanted to point out in case you weren't already aware, that releasing this as v2.2.2 also released all your 3.0.0-beta6 changes.

**Comment by bsutton** [comment]
Oh crap.
That was not the intent.

Will correct the 2.x release in the next couple of days.

Thanks for the head up

**Comment by bsutton** [comment]
@KOGI I've just published 2.2.3 which reverts the v3 beta api changes.

**Pull request merged**
